version: '3'

services:

  proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8080:80"
    environment:
      - VUE_APP_API_URL=http://backend
    networks:
      app-network:
        aliases:
          - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8081:80"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: toor
    networks:
      app-network:
        aliases:
          - backend

  mysql:
    image: mysql:latest
    platform: linux/x86_64
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: my_db
      MYSQL_USER: adm
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app-network:
        aliases:
          - mysql

networks:
  app-network:

volumes:
   mysql_data:
