version: '3'

services:

  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - backend
    environment:
      VUE_APP_BACKEND_ENDPOINT: http://api.app.loc
    networks:
      my-network:
        aliases:
          - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8081:80"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: toor
    networks:
      my-network:
        aliases:
          - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: my_db
      MYSQL_USER: adm
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      my-network:
        aliases:
          - mysql

volumes:
   mysql-data:

networks:
  my-network: