version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://api.loc

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "9000:9000"
    networks:
      - app-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password

  web:
    image: nginx
    container_name: nginx_container
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  mysql:
    image: mysql:latest
    platform: linux/x86_64
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
   mysql_data:
