version: '3'
services:
  frontend:
    build:
      context: ./app
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./api
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
